[build]
  command = "npm install && npm install --save-dev typescript @types/react @types/node @types/react-dom && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
