[build]
  command = "rm -rf node_modules package-lock.json && npm install --force && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
