[build]
  command = "./build.sh"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.0.0"
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
